import { useEffect, useState } from 'react'
import { api, post } from './api'
import { useCommunity } from './context'
type Report={id:string;module_id:string;author_login:string;title:string;body:string;status:string;created_at:string;github_url:string|null}
export function ActivityPage(){
 const {session,refresh}=useCommunity(),[reports,setReports]=useState<Report[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[confirming,setConfirming]=useState(false),[busy,setBusy]=useState(false)
 const guest=session.user
 useEffect(()=>{let cancelled=false;if(!session.available)return;void api<Report[]>('/issues/mine').then(items=>{if(!cancelled)setReports(items)}).catch(error=>{if(!cancelled)setError(error.message)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[session.available,guest?.id])
 async function forget(){setBusy(true);setError('');try{await post('/auth/logout',{});await refresh();setReports([]);setConfirming(false);setMessage('This device no longer holds a guest identity. Your earlier posts stay public until moderation removes them.')}catch(error){setError(error instanceof Error?error.message:'Unable to forget this guest identity.')}finally{setBusy(false)}}
 return <div className="community-page"><div className="page-heading"><div><p className="page-kicker">OCTAMOD / COMMUNITY</p><h1>Your activity</h1><p>Comments, ratings, likes and issue reports work without an account or email.</p></div><span className="pill">No sign-in</span></div>
  <section className="configuration-section"><div className="section-title"><h2>Your issue reports</h2>{!!reports.length&&<span className="pill">{reports.filter(item=>item.status==='open').length} open</span>}</div>{!session.available?<p className="service-note">Community services are not connected yet. Your configurations and firmware still work on this device.</p>:loading?<p role="status">Loading reports…</p>:reports.length?reports.map(item=><article className="inbox-issue" key={item.id}><div className="section-title"><h3>{item.title}</h3><span className="pill">{item.status==='open'?'Open':'Resolved'}</span></div><small>{item.module_id} · for @{item.author_login}{item.github_url&&<> · <a href={item.github_url} target="_blank" rel="noreferrer">Follow on GitHub ↗</a></>}</small><p className="preserve-lines">{item.body}</p></article>):!error&&<p className="service-note">No reports from this device. Use “Report an issue” on a module page.</p>}</section>
  <section className="configuration-section"><h2>Privacy on this device</h2><p className="service-note">Your first post creates an anonymous guest key, saved only in this browser. It lets you remove your own comments, change your rating and follow your reports. Octamod stores the name you type, your posts and a hashed copy of the key. It never asks for email and adds no analytics or tracking. Rate limits keep short-lived hashed keys, not raw IP addresses. Clearing site data removes the key.</p><p className="service-note">Comments, ratings and likes are public. Issue reports become public GitHub issues for the module author, with your name, report text, module list and attached OCTAMOD.LOG. The Octamod administrator also keeps a copy. Only this device can list your own reports here.</p>{guest&&(confirming?<div className="admin-withdraw"><h3>Forget guest identity?</h3><p>You will no longer be able to remove your earlier comments or follow your reports from this device. Posts are not deleted.</p><div className="review-actions"><button className="button button-quiet" disabled={busy} onClick={()=>setConfirming(false)}>Cancel</button><button className="button button-primary" disabled={busy} onClick={()=>void forget()}>{busy?'Forgetting…':'Forget on this device'}</button></div></div>:<button className="button button-quiet" onClick={()=>setConfirming(true)}>Forget guest identity on this device</button>)}</section>
  <section className="configuration-section"><h2>Contributing modules</h2><p className="service-note">New modules, updates, documentation and media go through GitHub pull requests. Octamod has no website sign-in.</p><a className="text-button" href="#submit">Module contribution guide →</a></section>
  {message&&<p className="success-note" role="status">{message}</p>}{error&&<p className="file-error" role="alert">{error}</p>}</div>
}
