import { useEffect, useState } from 'react'
import { api, post } from './api'
import { useCommunity } from './context'
import { FORUM_CATEGORIES, type ForumCategory, type ForumPost, type ForumThread, type SharedConfiguration, type ThreadDetail } from './forum-contract'
import { MODULES } from '../catalog/modules'
import { MemberPrompt } from './MemberPrompt'
import type { Configuration } from '../config/workspace'
function date(value:string){return new Date(value.includes('T')?value:value.replace(' ','T')+'Z').toLocaleString()}
function errorText(error:unknown){return error instanceof Error?error.message:'The request could not be completed.'}
function ThreadRows({threads}:{threads:ForumThread[]}){return <div className="forum-thread-list">{threads.map(thread=><article className="forum-thread-row" key={thread.id}><div><div className="forum-meta"><span>{FORUM_CATEGORIES[thread.category]}</span>{!!thread.pinned&&<span>Pinned</span>}{!!thread.locked&&<span>Locked</span>}{thread.category==='issues'&&<span>{thread.status==='resolved'?'Resolved':'Open'}</span>}</div><h2><a href={'#forum/thread/'+thread.id}>{thread.title}</a></h2><div className="forum-meta"><a href={'#forum/profile/'+thread.username}>@{thread.username}</a>{thread.module_id&&<a href={'#module/'+thread.module_id}>{MODULES.find(module=>module.id===thread.module_id)?.name??thread.module_id}</a>}<time>{date(thread.updated_at)}</time></div></div><span className="forum-reply-count">{thread.replies}<small>{thread.replies===1?'reply':'replies'}</small></span></article>)}</div>}
function ForumList({query,profile}:{query:URLSearchParams;profile?:string}){
  const {session}=useCommunity(),[data,setData]=useState<{threads:ForumThread[];hasMore:boolean}|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0)
  const serialized=query.toString(),category=query.get('category')??'',page=Number(query.get('page')??0)
  useEffect(()=>{let cancelled=false;void api<{threads:ForumThread[];hasMore:boolean}>('/forum/threads?'+serialized+(profile?'&author='+encodeURIComponent(profile):'')).then(value=>{if(!cancelled)setData(value)}).catch(error=>{if(!cancelled)setError(errorText(error))});return()=>{cancelled=true}},[serialized,profile,revision])
  function link(values:Record<string,string>){const next=new URLSearchParams(query);next.delete('page');for(const [key,value] of Object.entries(values)){if(value)next.set(key,value);else next.delete(key)}return '#forum?'+next.toString()}
  return <><div className="page-heading"><div><p className="page-kicker">OCTAMOD / COMMUNITY</p><h1>{profile?'@'+profile:'Community forum'}</h1><p>{profile?'Public threads by this member.':'Share what you are making. Learn from each other.'}</p></div><a className="button button-primary" href={session.user?.verified?'#forum/new':'#account/register'}>Start a thread</a></div>
    {!profile&&<><nav className="forum-categories" aria-label="Forum categories"><a className={!category&&!query.has('saved')?'active':''} href="#forum">Latest</a>{Object.entries(FORUM_CATEGORIES).map(([key,label])=><a key={key} className={category===key?'active':''} href={link({category:key,saved:''})}>{label}</a>)}{session.user?.verified&&<a className={query.has('saved')?'active':''} href={link({saved:'1',category:''})}>Bookmarks</a>}</nav><form className="forum-filters" onSubmit={event=>{event.preventDefault();const values=new FormData(event.currentTarget);window.location.assign(link({q:String(values.get('q')??''),module:String(values.get('module')??'')}))}}><label><span className="sr-only">Search discussions</span><input name="q" type="search" defaultValue={query.get('q')??''} maxLength={120} placeholder="Search discussions…"/></label><label><span className="sr-only">Filter by module</span><select name="module" defaultValue={query.get('module')??''}><option value="">All modules</option>{MODULES.map(module=><option key={module.id} value={module.id}>{module.name}</option>)}</select></label><button className="button button-quiet">Search</button></form></>}
    {error?<p className="file-error" role="alert">{error} <button className="text-button" onClick={()=>{setError('');setRevision(value=>value+1)}}>Try again</button></p>:!data?<p role="status">Loading discussions…</p>:data.threads.length?<ThreadRows threads={data.threads}/>:<div className="forum-empty"><h2>{profile?'No public threads yet':'No discussions here yet'}</h2><p>{query.get('q')?'Try a different search or module filter.':'Start with a question, a useful tip or a configuration you enjoy.'}</p><a className="button button-quiet" href="#forum/new">Start a thread</a></div>}
    <div className="forum-pagination">{page>0&&<a href={link({page:String(page-1)})}>← Previous</a>}{data?.hasMore&&<a href={link({page:String(page+1)})}>Next →</a>}</div><MemberPrompt/>
  </>
}
function NewThread({configuration,query}:{configuration?:Configuration;query:URLSearchParams}){
  const {session}=useCommunity(),[category,setCategory]=useState<ForumCategory>((Object.hasOwn(FORUM_CATEGORIES,query.get('category')??'')?query.get('category'):'general') as ForumCategory),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  async function submit(form:HTMLFormElement){setBusy(true);setError('');try{const values=Object.fromEntries(new FormData(form)),payload:Record<string,unknown>={title:values.title,body:values.body,category,moduleId:values.moduleId};if(category==='configs'){if(!configuration)throw new Error('Create a local configuration first.');payload.configuration={name:configuration.name,moduleIds:configuration.moduleIds,moduleVersions:configuration.moduleVersions,keepStockFx2:configuration.keepStockFx2}}if(category==='issues')payload.issue={device:values.device,version:values.version,steps:values.steps,expected:values.expected,actual:values.actual};const result=await post<{id:string}>('/forum/threads',payload);window.location.assign('#forum/thread/'+result.id)}catch(error){setError(errorText(error))}finally{setBusy(false)}}
  return <><a className="back-link" href="#forum">← Forum</a><div className="page-heading"><div><h1>Start a conversation</h1><p>A question, a discovery or a configuration worth sharing.</p></div></div><MemberPrompt/>{session.user?.verified&&<form className="community-form forum-composer" onSubmit={event=>{event.preventDefault();void submit(event.currentTarget)}}><label>Category<select value={category} onChange={event=>setCategory(event.target.value as ForumCategory)}>{Object.entries(FORUM_CATEGORIES).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Title<input name="title" required maxLength={160} placeholder="What would you like to discuss?"/></label><label>{category==='issues'?'Affected module':'Related module (optional)'}<select name="moduleId" required={category==='issues'} defaultValue={query.get('module')??''}><option value="">Choose a module</option>{MODULES.map(module=><option key={module.id} value={module.id}>{module.name}</option>)}</select></label>
    {category==='configs'&&<aside className="forum-config"><h2>{configuration?.name??'No configuration selected'}</h2><p>{configuration?.moduleIds.map(id=>(MODULES.find(module=>module.id===id)?.name??id)+' '+configuration.moduleVersions[id]).join(' · ')||'Add modules to a local configuration first.'}</p><p>This publishes a fixed copy of the selected configuration. Firmware stays on your device.</p><a href="#configuration">Review your configuration →</a></aside>}
    {category==='issues'&&<fieldset><legend>Reproduction details</legend><label>Octatrack model<select name="device" required><option value="">Choose a model</option><option>MKI</option><option>MKII</option><option>Both</option></select></label><label>Module version<input name="version" required maxLength={80}/></label><label>Steps to reproduce<textarea name="steps" required maxLength={4000} rows={4}/></label><label>Expected result<textarea name="expected" required maxLength={2000} rows={2}/></label><label>Actual result<textarea name="actual" required maxLength={2000} rows={2}/></label><p className="service-note">This thread is public. For sensitive details, use the private issue form on the module page.</p></fieldset>}
    <label>{category==='issues'?'Summary and context':'Your post'}<textarea name="body" required maxLength={12000} rows={8} placeholder="Share enough detail for others to join in…"/></label><p className="service-note">Posts are public. Share only original or properly licensed content. Do not post firmware, dumps, passwords or personal information. File uploads are not supported.</p><button className="button button-primary" disabled={busy||(category==='configs'&&!configuration?.moduleIds.length)}>{busy?'Publishing…':'Publish thread'}</button></form>}{error&&<p className="file-error" role="alert">{error}</p>}</>
}
function PostContent({body}:{body:string}){return <div className="forum-post-body">{body.split('\n').map((line,index)=>line.startsWith('>')?<blockquote key={index}>{line.replace(/^>\s?/,'')||' '}</blockquote>:<div key={index}>{line||'\u00a0'}</div>)}</div>}
function PostCard({item,locked,refresh,onQuote}:{item:ForumPost;locked:boolean;refresh:()=>Promise<void>;onQuote:(value:string)=>void}){
  const {session}=useCommunity(),[editing,setEditing]=useState(false),[body,setBody]=useState(item.body),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
  async function act(path:string,payload:unknown,method='POST'){setBusy(true);setError('');try{await post(path,payload,method);setEditing(false);await refresh();return true}catch(error){setError(errorText(error));return false}finally{setBusy(false)}}
  return <article className="forum-post" id={'post-'+item.id}><header><a href={'#forum/profile/'+item.username}>{item.username?'@'+item.username:'Removed post'}</a><time>{date(item.created_at)}</time>{item.edited_at&&<small>Edited</small>}{!!item.hidden&&<span className="pill">Hidden</span>}</header>{item.hidden&&!session.admin?<p className="service-note">This post was removed.</p>:editing?<form className="community-form" onSubmit={event=>{event.preventDefault();void act('/forum/posts/'+item.id,{body},'PATCH')}}><label>Edit your post<textarea value={body} onChange={event=>setBody(event.target.value)} required maxLength={12000} rows={6}/></label><div className="forum-actions"><button className="button button-primary" disabled={busy}>Save changes</button><button type="button" className="button button-quiet" onClick={()=>setEditing(false)}>Cancel</button></div></form>:<PostContent body={item.body}/>}
    {!!session.user?.verified&&!item.hidden&&<div className="forum-actions"><button className="text-button" disabled={busy} aria-pressed={item.liked} onClick={()=>void act('/forum/posts/'+item.id+'/react',{liked:!item.liked})}>{item.liked?'♥':'♡'} {item.likes}</button>{!locked&&<button className="text-button" onClick={()=>onQuote('> @'+item.username+' wrote:\n'+item.body.split('\n').map(line=>'> '+line).join('\n')+'\n\n')}>Quote</button>}{item.canEdit&&<button className="text-button" onClick={()=>{setBody(item.body);setEditing(true)}}>Edit</button>}<details><summary>Report</summary><form className="community-form" onSubmit={event=>{event.preventDefault();const reason=new FormData(event.currentTarget).get('reason');void act('/forum/posts/'+item.id+'/report',{reason}).then(ok=>{if(ok)setNotice('Report submitted to the administrator.')})}}><label>Reason<textarea name="reason" required maxLength={1000} rows={2}/></label><button className="button button-quiet" disabled={busy}>Send report</button></form></details></div>}
    {session.admin&&<details><summary>Moderate post</summary><form className="community-form" onSubmit={event=>{event.preventDefault();const fields=Object.fromEntries(new FormData(event.currentTarget));void act('/admin/forum/'+(fields.action==='suspended'?'users/'+item.user_id:'posts/'+item.id),{action:fields.action,value:fields.action==='hidden'?!item.hidden:true,reason:fields.reason},'PATCH')}}><label>Action<select name="action"><option value="hidden">{item.hidden?'Restore post':'Hide post'}</option><option value="suspended">Suspend author</option></select></label><label>Reason<input name="reason" required maxLength={1000}/></label><button className="button button-quiet" disabled={busy}>Apply</button></form></details>}{notice&&<p role="status">{notice}</p>}{error&&<p className="file-error" role="alert">{error}</p>}</article>
}
function ThreadPage({id,query,onCopy}:{id:string;query:URLSearchParams;onCopy:(config:SharedConfiguration)=>void}){
  const {session}=useCommunity(),[data,setData]=useState<ThreadDetail|null>(null),[error,setError]=useState(''),[reply,setReply]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
  const page=Number(query.get('page')??0)
  async function load(){setData(await api<ThreadDetail>('/forum/threads/'+id+'?page='+page))}
  useEffect(()=>{let cancelled=false;void api<ThreadDetail>('/forum/threads/'+id+'?page='+page).then(value=>{if(!cancelled)setData(value)}).catch(error=>{if(!cancelled)setError(errorText(error))});return()=>{cancelled=true}},[id,page])
  async function act(action:string,payload:unknown,method='POST'){setBusy(true);setError('');try{await post('/forum/threads/'+id+'/'+action,payload,method);await load();if(action==='replies'){setReply('');setNotice('Reply posted.')}}catch(error){setError(errorText(error))}finally{setBusy(false)}}
  if(!data)return <><a href="#forum">← Forum</a>{error?<p className="file-error" role="alert">{error}</p>:<p role="status">Loading thread…</p>}</>
  const {thread}=data
  return <><a className="back-link" href="#forum">← Forum</a><div className="page-heading"><div><p className="page-kicker">{FORUM_CATEGORIES[thread.category]}</p><h1>{thread.title}</h1><div className="forum-meta"><a href={'#forum/profile/'+thread.username}>@{thread.username}</a><time>{date(thread.created_at)}</time>{!!thread.locked&&<span>Locked</span>}{thread.category==='issues'&&<span>{thread.status==='resolved'?'Resolved':'Open'}</span>}</div></div></div>
    {session.user?.verified&&<div className="forum-actions"><button className="button button-quiet" disabled={busy} aria-pressed={data.following} onClick={()=>void act('follow',{enabled:!data.following})}>{data.following?'Following':'Follow replies'}</button><button className="button button-quiet" disabled={busy} aria-pressed={data.bookmarked} onClick={()=>void act('bookmark',{enabled:!data.bookmarked})}>{data.bookmarked?'Bookmarked':'Bookmark'}</button>{thread.category==='issues'&&(thread.username===session.user.username||session.admin)&&<button className="button button-quiet" disabled={busy} onClick={()=>void act('status',{status:thread.status==='open'?'resolved':'open'},'PATCH')}>{thread.status==='open'?'Mark resolved':'Reopen'}</button>}</div>}
    {data.configuration&&<aside className="forum-config"><h2>{data.configuration.name}</h2><ul>{data.configuration.moduleIds.map(module=><li key={module}>{MODULES.find(item=>item.id===module)?.name??module} <span className="subtle">{data.configuration!.moduleVersions[module]}</span></li>)}</ul><p>Stock FX2 {data.configuration.keepStockFx2?'preserved':'compact'}. Copy this snapshot to review compatibility and module availability before building.</p><button className="button button-primary" onClick={()=>{try{onCopy(data.configuration!)}catch(error){setError(errorText(error))}}}>Copy to my configurations</button></aside>}
    {data.issue&&<section className="forum-config"><h2>Reproduction details</h2><p>{data.issue.device} · {thread.module_id} · {data.issue.version}</p>{(['steps','expected','actual'] as const).map(key=><div key={key}><h3>{key==='steps'?'Steps to reproduce':key==='expected'?'Expected result':'Actual result'}</h3><PostContent body={data.issue![key]}/></div>)}</section>}
    {session.admin&&<details className="forum-config"><summary>Moderate thread</summary><form className="community-form" onSubmit={event=>{event.preventDefault();const fields=Object.fromEntries(new FormData(event.currentTarget));setError('');void post('/admin/forum/threads/'+id,{action:fields.action,value:fields.value==='true',reason:fields.reason},'PATCH').then(load).catch(error=>setError(errorText(error)))}}><label>Action<select name="action"><option value="locked">Lock</option><option value="pinned">Pin</option><option value="hidden">Hide</option></select></label><label>Set to<select name="value"><option value="true">On</option><option value="false">Off</option></select></label><label>Reason<input name="reason" required maxLength={1000}/></label><button className="button button-quiet">Apply</button></form></details>}
    {data.posts.map(item=><PostCard key={item.id} item={item} locked={!!thread.locked} refresh={load} onQuote={value=>{setReply(current=>current+value);document.getElementById('forum-reply')?.focus()}}/>)}<div className="forum-pagination">{page>0&&<a href={'#forum/thread/'+id+'?page='+(page-1)}>← Previous replies</a>}{data.hasMore&&<a href={'#forum/thread/'+id+'?page='+(page+1)}>More replies →</a>}</div>
    <MemberPrompt/>{thread.locked?<p className="service-note">This thread is locked. You can still read and bookmark it.</p>:session.user?.verified&&<form className="community-form forum-composer" onSubmit={event=>{event.preventDefault();void act('replies',{body:reply})}}><label htmlFor="forum-reply">Join the discussion</label><textarea id="forum-reply" value={reply} onChange={event=>setReply(event.target.value)} required maxLength={12000} rows={5} placeholder="Write a reply…"/><button className="button button-primary" disabled={busy||!reply.trim()}>{busy?'Posting…':'Post reply'}</button></form>}{notice&&<p className="success-note" role="status">{notice}</p>}{error&&<p className="file-error" role="alert">{error}</p>}</>
}
export function ForumPage({route,configuration,onCopy}:{route:string;configuration?:Configuration;onCopy:(config:SharedConfiguration)=>void}){
  const [path,search='']=route.split('?'),query=new URLSearchParams(search),segments=path.split('/')
  return <div className="community-page forum-page">{segments[1]==='new'?<NewThread configuration={configuration} query={query}/>:segments[1]==='thread'&&segments[2]?<ThreadPage key={segments[2]+'?'+search} id={segments[2]} query={query} onCopy={onCopy}/>:<ForumList key={search+segments[2]} query={query} profile={segments[1]==='profile'?segments[2]:undefined}/>}</div>
}
