import { useEffect, useState } from 'react'
import { api, post } from './api'
type Issue = { id: string; module_id: string; author_login: string; title: string; body: string; status: string; reporter: string }
export function IssueInbox({moduleId = '',onClearModule}: {moduleId?: string;onClearModule?: () => void}) {
  const [status,setStatus] = useState(moduleId ? 'open' : 'all')
  const path = '/admin/issues?status='+status+(moduleId ? '&moduleId='+encodeURIComponent(moduleId) : '')
  const [items, setItems] = useState<Issue[]>([]), [error, setError] = useState(''), [loading, setLoading] = useState(true), [busy, setBusy] = useState('')
  useEffect(() => { let cancelled = false; void api<Issue[]>(path).then(items => { if (!cancelled) setItems(items) }).catch(error => { if (!cancelled) { setItems([]); setError(error.message) } }).finally(() => { if (!cancelled) setLoading(false) }); return () => { cancelled = true } }, [path])
  async function resolve(item: Issue) { setBusy(item.id); setError(''); try { await post('/admin/issues/' + item.id, { status: item.status === 'open' ? 'closed' : 'open' }, 'PATCH'); setItems(await api<Issue[]>(path)) } catch (error) { setError(error instanceof Error ? error.message : 'Unable to update issue.') } finally { setBusy('') } }
  return <section className="configuration-section"><div className="section-title"><h2>Author-directed issues</h2><span className="pill">{items.filter(item => item.status === 'open').length} open</span></div><p className="service-note">Reports are private to the administrator and the reporting device. Pass each report on to its module author; resolving it updates the reporter’s status.</p><div className="statistics-controls inbox-controls"><label>Issue status<select value={status} disabled={!!busy} onChange={event => { setStatus(event.target.value); setLoading(true); setError('') }}><option value="all">All reports</option><option value="open">Open reports</option><option value="closed">Resolved reports</option></select></label>{moduleId && <span className="service-note">Module: {moduleId} <button className="text-button" onClick={onClearModule}>Clear module filter</button></span>}</div>{items.length===200 && <p className="service-note">Showing the latest 200 matching reports.</p>}{loading ? <p role="status">Loading reports…</p> : items.length ? items.map(item => <article className="inbox-issue" key={item.id}><div className="section-title"><h3>{item.title}</h3><span className="pill">{item.status}</span></div><small>{item.module_id} · from {item.reporter} · for @{item.author_login}</small><p>{item.body}</p><button className="text-button" disabled={!!busy} onClick={() => void resolve(item)}>{busy === item.id ? 'Saving…' : item.status === 'open' ? 'Mark resolved' : 'Reopen'}</button></article>) : !error && <p className="service-note">No reports match these filters.</p>}{error && <p className="file-error" role="alert">{error}</p>}</section>
}
