import { readFile, mkdir, readdir, copyFile, writeFile, access } from 'node:fs/promises'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseModuleDocument } from '../src/catalog/module-contract.ts'
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),args=process.argv.slice(2),id=args[0]
const option=(name,fallback)=>{const i=args.indexOf(name);return i<0?fallback:args[i+1]}
const kind=option('--kind','dsp'),author=option('--author',''),output=option('--output',null)
if(!id||!['dsp','coldfire'].includes(kind)||!author)throw new Error('Usage: npm run module:new -- my-filter --kind dsp|coldfire --author github-login')
const document=JSON.parse(await readFile(resolve(root,'public/module-repository.example.json'),'utf8'))
document.id=id;document.key=id.toUpperCase().replaceAll('-',' ');document.name=id.split('-').map(word=>word[0]?.toUpperCase()+word.slice(1)).join(' ');document.author={github:author,credits:[author]}
if(kind==='coldfire'){document.category='playback';document.compatibility.location='Flex / Static';document.compatibility.effectId=null;document.controls=[]}
parseModuleDocument(document)
const destination=output?resolve(output,id):resolve(root,'sdk/octabam/modules',id)
try{await access(destination);throw new Error('Destination exists; refusing to replace a module: '+destination)}catch(error){if(error.code!=='ENOENT')throw error}
await mkdir(destination,{recursive:true});await mkdir(resolve(destination,'media'))
const template=resolve(root,'sdk/templates',kind),placeholder=kind==='dsp'?'_template':'_template_cf'
for(const file of await readdir(template)){if(file==='manifest.py'){let source=await readFile(resolve(template,file),'utf8');source=source.replaceAll('__AUTHOR__',author).replaceAll(placeholder,id).replaceAll(kind==='dsp'?'TEMPLATE':'TEMPLATE CF',document.key);await writeFile(resolve(destination,file),source)}else await copyFile(resolve(template,file),resolve(destination,file))}
await writeFile(resolve(destination,'octamod.module.json'),JSON.stringify(document,null,2)+'\n')
await copyFile(resolve(root,'sdk/octabam/LICENSE'),resolve(destination,'LICENSE'))
await copyFile(resolve(root,'public/module-qualification.example.json'),resolve(destination,'qualification.example.json'))
await writeFile(resolve(destination,'README.md'),`# ${document.name}\n\nVersion: ${document.version} · author: @${author}\n\n## Overview\n\nDescribe the sound, signal path and practical uses. This scaffold has not been tested.\n\n## Controls\n\nDocument every active control, defaults, ranges, modes and interactions. Keep octamod.module.json synchronized.\n\n## Usage\n\nGive a useful starting configuration, prerequisites and the exact OT button/menu sequence. Keep the manifest access.location and access.steps synchronized.\n\n## Quick tutorial\n\nPublication requires at least three practical steps: setup/select, use the controls with an example, and verify the result/reset. Replace these draft instructions with actual steps and keep tests.qualification.documentation.tutorial synchronized.\n\n## Compatibility and limitations\n\nDeclare supported hardware, base OS, slots, memory claims and conflicts. Do not publish unverified claims. DSP scaffolds start with an example effect ID: choose a free ID and add gate evidence before use.\n\n## Tests and measurements\n\nSee [TESTING.md](TESTING.md). Draft costs must remain explicitly unmeasured. New modules and updates cannot pass publication checks until tests.qualification records worst-case cycles under modulation, exact memory accounting and passed real hardware stress-project evidence. See docs/MODULE_QUALIFICATION.md and the qualification.example.json template.\n\n## Authorship and licences\n\nRetain original authors and component licence texts. Only original or properly licensed code/media; no Elektron firmware, extracted routines or tables.\n\n## Screens and audio\n\nPublication requires complete README sections, a short tutorial and real black-and-white PNG screenshots in the same style as the online modules. Yellow/colored screenshots fail release validation. Capture with the monochrome MKII renderer; never substitute a reconstruction. Include screenshots and tutorial steps in tests.qualification.documentation and keep README synchronized. Publication requires real OT UI captures showing the chooser/enable location and all relevant main/setup/control pages. Capture hardware LCD pixels or the headless emulator framebuffer. Put PNG/JPEG/WebP images under media/, declare captions, alt text, authorship, rights and otUi page/version/build/setup provenance in the manifest, and reference them from access.screenshots. The empty screenshot list is draft-only; illustrations and reconstructed labels do not qualify. See docs/MODULE_UI_CAPTURES.md in the repository. Audio is optional.\n`)
await writeFile(resolve(destination,'TESTING.md'),`# ${document.name} testing\n\n## Commands and exact revision\n\nNo checks have been run. Record the tested source commit and every command/result after implementation.\n\n## Stress and audio quality\n\nRequire at least 60 minutes on real MKI or MKII hardware with all eight audio tracks active. Exercise parameter extremes, simultaneous LFOs/p-locks/MIDI/scene modulation, mode/Part/bypass changes and maximum voices/instances; document inapplicable cases with reasons. Record tester, date, project recipe/fingerprint, local firmware build SHA-256, native-source SHA-256, workload, duration and actual results. Audio continuity, transport, controls, memory integrity and recovery must all pass. Separate emulator evidence from hardware results.\n\n## Resources\n\nUnmeasured: publication is blocked. Record worst-case cycles for every processor used, per-instance and maximum configuration, units and real-time budget, including branch/mode changes and modulation. Inventory exact code/state/table/buffer/stack/heap/padding memory by address space, word width, words, bytes and instance/shared scope. Include per-instance, shared and maximum-instance totals; compare against the native allocation/build report. Attach local text reports, never firmware or project/card dumps. Fill tests.qualification only with actual results.\n\n## Hardware\n\nUntested. Never infer hardware safety from assembly or a green metadata check.\n\n## OT UI capture evidence\n\nPending: capture the actual location and relevant control pages. Record the local image SHA-256, module version, emulator source/binary identity or hardware model, prerequisites, panel sequence and exact capture commands. Retain only screenshots and metadata; never firmware, memory dumps, cards or private logs. UI captures do not establish audio or hardware qualification.\n`)
console.log('Created '+destination+'\nImplement the native source, choose a free effect ID where applicable, and complete qualification.example.json with actual measurements and hardware stress results before proposing a PR. Copy the completed object into tests.qualification; the draft cannot pass publication checks.')
